import AppKit
import Foundation
import ImageIO

// swift scripts/brand-assets.swift
// The production SVG is the only shape source; no dependency on local design proposals.
let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let svg = try String(contentsOf: root.appendingPathComponent("public/icon.svg"), encoding: .utf8)
let match = try NSRegularExpression(pattern: "<path id=\"phrase\" d=\"([^\"]+)\"")
    .firstMatch(in: svg, range: NSRange(svg.startIndex..., in: svg))!
let data = String(svg[Range(match.range(at: 1), in: svg)!])
let tokenRegex = try NSRegularExpression(pattern: "[MHVCLZ]|-?[0-9]+(?:\\.[0-9]+)?")
let tokens = tokenRegex.matches(in: data, range: NSRange(data.startIndex..., in: data))
    .map { String(data[Range($0.range, in: data)!]) }
let shape = CGMutablePath()
var index = 0
func number() -> CGFloat {
    defer { index += 1 }
    return CGFloat(Double(tokens[index])!)
}
while index < tokens.count {
    let command = tokens[index]
    index += 1
    switch command {
    case "M": shape.move(to: CGPoint(x: number(), y: number()))
    case "L": shape.addLine(to: CGPoint(x: number(), y: number()))
    case "H": shape.addLine(to: CGPoint(x: number(), y: shape.currentPoint.y))
    case "V": shape.addLine(to: CGPoint(x: shape.currentPoint.x, y: number()))
    case "C":
        let a = CGPoint(x: number(), y: number())
        let b = CGPoint(x: number(), y: number())
        let end = CGPoint(x: number(), y: number())
        shape.addCurve(to: end, control1: a, control2: b)
    case "Z": shape.closeSubpath()
    default: fatalError("Unsupported SVG command: \(command)")
    }
}

func color(_ hex: UInt32) -> CGColor {
    CGColor(colorSpace: CGColorSpace(name: CGColorSpace.sRGB)!,
            components: [CGFloat((hex >> 16) & 255) / 255,
                         CGFloat((hex >> 8) & 255) / 255,
                         CGFloat(hex & 255) / 255, 1])!
}
let mint = color(0xC9F3EC)
let teal = color(0x123F46)
let lake = color(0x087E8B)
let porcelain = color(0xF6F8F5)

func mark(_ c: CGContext) {
    for (x, y) in [(108.0, 208.0), (276.0, 138.0)] {
        c.saveGState()
        c.translateBy(x: x, y: y)
        c.addPath(shape)
        c.fillPath()
        c.restoreGState()
    }
}

func png(_ path: String, width: Int, height: Int? = nil,
         draw: (CGContext, CGFloat, CGFloat) -> Void) throws {
    let h = height ?? width
    let c = CGContext(data: nil, width: width, height: h, bitsPerComponent: 8,
                      bytesPerRow: width * 4, space: CGColorSpace(name: CGColorSpace.sRGB)!,
                      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    c.translateBy(x: 0, y: CGFloat(h))
    c.scaleBy(x: 1, y: -1)
    draw(c, CGFloat(width), CGFloat(h))
    let url = root.appendingPathComponent(path)
    let target = CGImageDestinationCreateWithURL(url as CFURL, "public.png" as CFString, 1, nil)!
    CGImageDestinationAddImage(target, c.makeImage()!, nil)
    precondition(CGImageDestinationFinalize(target))
}

func icon(_ path: String, size: Int, radius: CGFloat = 112, foreground: Bool = false,
          maskScale: CGFloat = 1) throws {
    try png(path, width: size) { c, w, h in
        c.scaleBy(x: w / 512, y: h / 512)
        if !foreground {
            c.setFillColor(teal)
            c.addPath(CGPath(roundedRect: CGRect(x: 0, y: 0, width: 512, height: 512),
                             cornerWidth: radius, cornerHeight: radius, transform: nil))
            c.fillPath()
        }
        let scale: CGFloat = foreground ? 2 / 3 : maskScale
        c.translateBy(x: 256 * (1 - scale), y: 256 * (1 - scale))
        c.scaleBy(x: scale, y: scale)
        c.setFillColor(mint)
        mark(c)
    }
}

for size in [192, 512] {
    try icon("public/icon-\(size).png", size: size)
}
try icon("public/icon-maskable-512.png", size: 512, radius: 0, maskScale: 0.9)
let res = "android/app/src/main/res"
for (density, size, foregroundSize) in [
    ("mdpi", 48, 108), ("hdpi", 72, 162), ("xhdpi", 96, 216),
    ("xxhdpi", 144, 324), ("xxxhdpi", 192, 432)
] {
    try icon("\(res)/mipmap-\(density)/ic_launcher.png", size: size)
    try icon("\(res)/mipmap-\(density)/ic_launcher_round.png", size: size, radius: 256)
    try icon("\(res)/mipmap-\(density)/ic_launcher_foreground.png", size: foregroundSize, foreground: true)
}

func vector(foreground: String, viewport: Int = 768) -> String {
    let shift = (viewport - 512) / 2
    return """
    <?xml version="1.0" encoding="utf-8"?>
    <!-- Generated by scripts/brand-assets.swift from public/icon.svg. -->
    <vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="108dp" android:height="108dp"
        android:viewportWidth="\(viewport)" android:viewportHeight="\(viewport)">
        <group android:translateX="\(shift)" android:translateY="\(shift)">
            <group android:translateX="108" android:translateY="208">
                <path android:fillColor="\(foreground)" android:pathData="\(data)"/>
            </group>
            <group android:translateX="276" android:translateY="138">
                <path android:fillColor="\(foreground)" android:pathData="\(data)"/>
            </group>
        </group>
    </vector>

    """
}
for (path, contents) in [
    ("drawable-v24/ic_launcher_foreground.xml", vector(foreground: "#C9F3EC")),
    ("drawable/ic_locue_monochrome.xml", vector(foreground: "#FFFFFF")),
    ("drawable/ic_locue_splash.xml", vector(foreground: "#087E8B", viewport: 768))
] {
    try contents.write(to: root.appendingPathComponent("\(res)/\(path)"), atomically: true, encoding: .utf8)
}

// Also update legacy splash rasters so older Android versions do not show the old brand.
let resURL = root.appendingPathComponent(res)
for directory in try FileManager.default.contentsOfDirectory(at: resURL, includingPropertiesForKeys: nil)
    where directory.lastPathComponent.hasPrefix("drawable") {
    let file = directory.appendingPathComponent("splash.png")
    guard FileManager.default.fileExists(atPath: file.path),
          let source = CGImageSourceCreateWithURL(file as CFURL, nil),
          let original = CGImageSourceCreateImageAtIndex(source, 0, nil) else { continue }
    try png("\(res)/\(directory.lastPathComponent)/splash.png",
            width: original.width, height: original.height) { c, w, h in
        c.setFillColor(porcelain)
        c.fill(CGRect(x: 0, y: 0, width: w, height: h))
        let size = min(w, h) * 0.3
        c.translateBy(x: (w - size) / 2, y: (h - size) / 2)
        c.scaleBy(x: size / 512, y: size / 512)
        c.setFillColor(lake)
        mark(c)
    }
}
print("Locue web icons, Android launcher layers, monochrome and splash assets generated.")
